# fly.toml app configuration file generated for imitari on 2023-09-20T11:28:49-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "imitari"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
